[project]
name = "mapsearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "googlemaps>=4.10.0",
    "requests>=2.32.4",
    "selenium>=4.34.2",
]
